---
title: "ENVS 193DS Final"
author: "Helena Parsons"
format: pdf
editor: visual
---

# Link to Github repo

https://github.com/hparsons333/ENVS-193DS_spring-2026_final

# Setting up

```{r loading-packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
```

# Problem 1. Research writing

**You’re working on a research team trying to understand how restoration of native plant cover (measured in percent cover) influences probability of American Avocet (Recurvirostra americana) and other shorebird habitat use in the San Francisco Bay. Your co-worker runs some analyses and writes up a report, giving it to you to review. In part 1 of the results section of the report, your co-worker has written:**

***We rejected the null hypothesis that distance to water edge does not predict probability of American Avocet microhabitat use (p = 0.03).***

**In part 2 of the results section of the report, your co-worker has written:**

***We rejected the null hypothesis that there is no relationship between bird species (American Avocet, Forster’s Tern, Black-necked Stilt) and habitat (managed pond, non-tidal marsh, salt pond, tidal marsh, or tidal mudflat) (p < 0.001).***

**It’s great that this report is coming together, but you think they can improve on what they’ve written and make it more understandable to a non-statistical audience.**

## 1a. Transparent statistical methods

**What statistical tests did your co-worker use?**

**Clearly connect the test to the part that you are addressing (e.g. “In part 1, they used _______. In part 2, they used _______.”).**

In part 1, they used a simple linear regression to test if distance to water edge predicted American Avocet microhabitat use. In part 2, they used a correlation coefficient test to see if there was a relationship between bird species and habitat.

## 1b. Suggestions for rewriting

**In 1-3 sentences, write new statements with interpretation only for the statements in part a and b.**

**Be sure your interpretation makes sense without any statistical summary (which, again, you should not include).**

### Rewriting statement a

Our results suggest that we can reject the null hypothesis that distance to water edge does not predict probability of American Avocet microhabitat use. Alternatively, we determine that the distance to water edge significantly predicts American Avocent microhabitat use. 

### Rewriting statement b. 

Our results suggest that we can reject the null hypothesis, which states that there is no relationship between the type of bird species found and the habitat type. Alternatively, we determine that there is a significant relationship between the type of bird species found and the habitat type.






